### ISSUE TITLE
Changing netspeed doesn't work when you weren't the person that added the server.

### ISSUE THREAD

**Issue by Jas0n99** [abh/ntppool#183]
It appears that you can only change the netspeed for servers that you added initially.

This should instead be changed to allow any of the team on the account to change the netspeed.

**Comment by abh** [comment]
A user reported this too (in [RT#7083](https://rt.ntppool.org/Ticket/Display.html?id=7089); either the same user id thing or because it was a secondary account.

When I searched in the logs I noticed that I don't think that API call was updated to use the account id token, so the code is probably still checking on user_id.

**Comment by abh** [comment]
This should be fixed on the beta site: https://manage-beta.grundclock.com/manage/

**Comment by Jas0n99** [comment]
Looks like it is working now!

**Comment by Jas0n99** [comment]
Well, I think it's broken again... Not sure what changed but it just 'freezes' like before, and a refresh of the page loads the old netspeed. You can still change server's that you created originally, just not others, even if they are now in your team account...
